server: 
    port: 8081
local:
  server:
    port: 8081
spring: 
    application:   
        name: gateway-service
    cloud: 
        gateway: 
            discovery: 
                locator: 
                    enabled: true
                    lower-case-service-id: true
            routes:
            - id : consumers-find-all
              uri: lb://consumer-service/consumers
              predicates:
                - Path= /consumers
              filters:
              - AddRequestHeader=X-Request-Test, Header-From-Gateway  
            - id: consumers-strip-prefix
              uri: lb://consumer-service
              predicates:
              - Path=/consumers/test/delay
              filters:
              - StripPrefix=2